Breadcrumbs
vaultec81/blasio-app pull request #4
Opened 2020-08-27 18:01 UTC by olatundeee

Added a new component <TopNavbar /> that handles the dynamic breadcrumb functionality

2020-08-27 23:14 UTC, vaultec81 requested changes
Checklist
- [x] Resolve merge conflicts
- [x] Implement forward and back buttons
- [x] Implement an ability to copy current URL and paste URL into navbar (In doing so would direct to the page of input)
- [x] Revert any Linters/prettifiers
- [x] Provide screenshot of changes

A small note on linting. Generally speaking I've seen the use of excessive prettifiers/linters problematic in large projects. Please keep the usage of them at a minimum. I will be adding a universal lint command sometime soon.

2020-08-27 23:14 UTC, vaultec81 commented on src/renderer/components/Navbar.js
> +            <div>
Any particular reason why you added an extra div tag enclosing the navbar?

2020-08-27 23:14 UTC, vaultec81 commented on src/renderer/components/TopNavbar.js
> +                        <Breadcrumb.Item href="/">Home</Breadcrumb.Item>
We use react router's hashrouter, which means all links must start with `#/` including the root directory.

2020-08-27 23:14 UTC, vaultec81 commented on src/renderer/components/TopNavbar.js
> +                            <Breadcrumb.Item href="#" key={el}>{el}</Breadcrumb.Item>
Make sure to dynamically generate the href from url.

2020-08-27 23:14 UTC, vaultec81 commented on src/renderer/components/TopNavbar.js
> +        const newUrl = urlSplit.splice(0, 4);
Unused variable?

2020-08-28 14:06 UTC, olatundeee commented on src/renderer/components/Navbar.js
> +            <div>
I have fixed this

2020-08-28 14:06 UTC, olatundeee commented on src/renderer/components/TopNavbar.js
> +                            <Breadcrumb.Item href="#" key={el}>{el}</Breadcrumb.Item>
Done

2020-08-28 14:06 UTC, olatundeee commented on src/renderer/components/TopNavbar.js
> +        const newUrl = urlSplit.splice(0, 4);
Done

2020-08-28 19:25 UTC, vaultec81 requested changes

2020-08-28 19:25 UTC, vaultec81 commented on src/renderer/App.js
> -            <Route path="/" exact>
There appears to be a regression here removing routes from main branch

2020-08-28 19:25 UTC, vaultec81 commented on src/renderer/components/TopNavbar.js
> +                console.log('done',);
Unnecessary `,`

2020-08-29 19:36 UTC, vaultec81 approved these changes

2020-08-29 19:37 UTC, merged